name = "hrt-tracker"
main = "worker.ts"
compatibility_date = "2025-12-04"

[assets]
directory = "./dist"

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "hrt-tracker-prod"
database_id = "916011c6-3b95-4116-a10e-76af94496170"

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = "mahiro-contents"

[vars]
JWT_SECRET = "a3f9c8d2e5b1a477363910284756291038475629103847562910384756291038"
